const ROUTES = {
  home: '/',
  treatments: '/tratamientos',
  checkout: {
    clinics: '/checkout/clinicas',
    type: '/checkout/tipo-cita',
    treatments: '/checkout/treatments',
    schedule: '/checkout/agenda',
    contactForm: '/checkout/contactform',
    thankYou: '/checkout/confirmation',
  },
  clinics: '/clinicas',
  aboutUs: '/quienes-somos',
  blog: '/blog',
  dashboard: {
    crisalix: '/dashboard/crisalix',
    menu: '/dashboard/menu',
    checkOut: '/dashboard/checkout',
    checkIn: {
      treatments: '/dashboard/checkin/treatments',
      agenda: '/dashboard/checkin/agenda',
      thankYou: '/dashboard/checkin/welcome',
      contactForm: '/dashboard/checkin/treatments',
      badRequest: '/dashboard/checkin/badRequest',
      confirmation: '/dashboard/checkin/confirmation',
    },
  },
  crm: {
    authentication: '/crm',
    menu: '/crm/menu',
  },
  statics: {
    termsAndConditions: '/aviso-legal',
    privacyPolicy: '/politica-de-privacidad',
  },
  landings: {
    pv: '/start-landing',
  },
  derma: {
    home: 'https://derma.holaglow.com',
    precios: '/derma/precios',
    clinics: '/derma/clinicas',
    aboutUs: '/derma/quienes-somos',
    multistep: {
      start: '/derma/multistep/start',
      pains: '/derma/multistep/pains',
      symptoms: '/derma/multistep/symptoms',
      skinType: '/derma/multistep/skin-type',
      skinSensibility: '/derma/multistep/skin-sensitivity',
      allergy: '/derma/multistep/allergy',
      illness: '/derma/multistep/illness',
      medication: '/derma/multistep/medication',
      lactating: '/derma/multistep/lactancy',
      gender: '/derma/multistep/gender',
      pictures: '/derma/multistep/pictures',
      extraInfo: '/derma/multistep/extra-info',
      form: '/derma/multistep/form',
      payment: '/derma/multistep/payment',
      thankyou: '/derma/multistep/thank-you',
      planes: '/derma/multistep/planes',
    },
  },
};

export default ROUTES;
