name: E2E tests

on:
  push:
    branches:
      - '**'

jobs:
  jobs:
  wait_for_deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Wait for 5 minutes
        run: sleep 300

  run_e2es:
    runs-on: ubuntu-latest
    steps:
      - name: Echo deployment status
        run: echo "Deployment status: ${{ github.event.deployment_status }}"
