name: Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  wait_for_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 5 minutes
        run: sleep 30

  run_e2es:
    needs: wait_for_deployment
    runs-on: ubuntu-latest
    steps:
      - name: Echo deployment status
        run: echo "Deployment status: ${{ github.event.deployment_status }}"