name: Show commit + branch information

on:
  push:

jobs:
  wait_for_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Just commit + branch information
        run: echo "Just commit + branch information"
